import { FormEvent, useState } from 'react';
import { services } from '../data/siteData';
import type { ContactFormData, ContactFormErrors } from '../types';
const initialForm:ContactFormData={name:'',phone:'',email:'',service:'',message:''};
interface ContactFormProps { compact?:boolean; }
export function ContactForm({compact=false}:ContactFormProps):JSX.Element {
 const [form,setForm]=useState<ContactFormData>(initialForm); const [errors,setErrors]=useState<ContactFormErrors>({}); const [sent,setSent]=useState(false);
 const update=<K extends keyof ContactFormData>(key:K,value:ContactFormData[K]):void=>setForm(prev=>({...prev,[key]:value}));
 const validate=():ContactFormErrors=>{const next:ContactFormErrors={};if(!form.name.trim())next.name='กรุณากรอกชื่อ';if(!/^0\d{8,9}$/.test(form.phone.replace(/[- ]/g,'')))next.phone='กรุณากรอกเบอร์โทรที่ถูกต้อง';if(form.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email))next.email='รูปแบบอีเมลไม่ถูกต้อง';if(!form.service)next.service='กรุณาเลือกบริการ';if(!compact&&!form.message.trim())next.message='กรุณากรอกรายละเอียด';return next;};
 const submit=(e:FormEvent<HTMLFormElement>):void=>{e.preventDefault();const next=validate();setErrors(next);if(Object.keys(next).length===0){setSent(true);setForm(initialForm);}};
 return <form noValidate onSubmit={submit} className="space-y-4">{sent&&<div className="rounded-xl bg-green-50 p-4 text-sm font-medium text-green-800">ส่งข้อมูลสำเร็จ ทีมงานจะติดต่อกลับโดยเร็ว</div>}<label className="block text-sm font-medium">ชื่อ-นามสกุล *<input className="field mt-1" value={form.name} onChange={e=>update('name',e.target.value)}/>{errors.name&&<span className="text-xs text-red-600">{errors.name}</span>}</label><label className="block text-sm font-medium">เบอร์โทรศัพท์ *<input className="field mt-1" value={form.phone} onChange={e=>update('phone',e.target.value)}/>{errors.phone&&<span className="text-xs text-red-600">{errors.phone}</span>}</label><label className="block text-sm font-medium">อีเมล<input type="email" className="field mt-1" value={form.email} onChange={e=>update('email',e.target.value)}/>{errors.email&&<span className="text-xs text-red-600">{errors.email}</span>}</label><label className="block text-sm font-medium">บริการที่สนใจ *<select className="field mt-1" value={form.service} onChange={e=>update('service',e.target.value)}><option value="">เลือกบริการ</option>{services.map(service=><option key={service.id}>{service.title}</option>)}</select>{errors.service&&<span className="text-xs text-red-600">{errors.service}</span>}</label>{!compact&&<label className="block text-sm font-medium">ข้อความ *<textarea rows={5} className="field mt-1" value={form.message} onChange={e=>update('message',e.target.value)}/>{errors.message&&<span className="text-xs text-red-600">{errors.message}</span>}</label>}<button className="btn-primary w-full" type="submit">ส่งข้อมูลปรึกษา</button></form>;
}
